name: ageal
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  bloc: ^8.1.4
  dartz: null
  dio: ^5.5.0+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: null
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.9
  fluttertoast: ^8.2.7
  get_it: null
  go_router: ^14.2.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  lottie: ^3.0.0
  share_plus: ^10.0.2
  shared_preferences: null
  shimmer: ^3.0.0
  url_launcher: ^6.3.0
  video_player: ^2.9.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/video/
    - assets/anim/
    - assets/images/vectors/
  fonts:
    - family: JannaLT
      fonts:
        - asset: assets/fonts/JannaLT-Bold.ttf
flutter_intl:
  enabled: true
